# Creation date : 19.08.2024
# Created by : CSR
# Description (quelques indices) : 
# Le service PHP utilise nativement le port 80, ce port 80 est exposé sur le port 8080 de l'hôte.
# Le nom du conteneur sera php_container
# Le build sera fait en utilisant le fichier php.dockerfile


services:
      
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php_container
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html


